### ISSUE TITLE
Rose Belarusian

### ISSUE THREAD

**Issue by antikruk** [PaulSonOfLars/tgbot#105]
Hi, Update please Belarusian from crowdin.

**Comment by PaulSonOfLars** [comment]
Hi, 

I've updated rose's languages.

However, in the future, please keep all requests in roses telegram support chat. This is the wrong place for it :)

Thank you!

**Comment by Botino888** [comment]
Ok so can we...?

**Comment by PaulSonOfLars** [comment]
Can we do what, exactly?

As I said above, I've already updated rose to use the latest translations. 

This also isn't the place to talk about Rose. So please, ask your questions in the rose support chat.

**Comment by Botino888** [comment]
Tôi muốn 1 buổi hẹn thân mật với 1 cô gái lầu 2, liệu bạn có thể lấy quyền kiểm soát cơ thể để có thể tương tác với tôi ?

**Comment by PaulSonOfLars** [comment]
Deleted off topic and wildly irrelevant content above.
