### ISSUE TITLE
[Feature] Send rules to group chat instead of PM

### ISSUE THREAD

**Issue by Chan4077** [PaulSonOfLars/tgbot#11]
When I add a rule to a group chat, the rule gets saved and a message is shown. However, if I want to view the rules that I've set, it replies to tell me to go to the bot's PM to see the group chat rules. This can be troublesome especially when I have to click/tap on the "Start" button to actually see the group chat rules.

Having the bot to message the rules in the same chat will be better as it is less troublesome and so that people who join the group can see the rules of the group. However, this can also cause spam issues if the group is very popular.

So, is this intentional behaviour?

**Comment by MSF-Jarvis** [comment]
Sending rules to PM is the current behaviour and unlikely to change.

**Comment by PaulSonOfLars** [comment]
As you've pointed out yourself, this can cause spam issues. Group rules tend to be longer messages than others, and so risk clogging up the chat. That's the reason the bot sends the rules to PM.

I'd also argue that if your group chat is big enough to need rules, you've probably reached the point where you're trying to avoid extra spam.

If you're still REALLY looking to receive the rules in the same chat, consider setting a filter on `/rules`, or saving a note and getting it with `#rules`.

**Comment by Chan4077** [comment]
@PaulSonOfLars Thanks for your quick reply. I'll close this issue.
