### ISSUE TITLE
user_id  integer out of range

### ISSUE THREAD

**Issue by torcookie** [PaulSonOfLars/tgbot#111]
sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range

[SQL: INSERT INTO users (user_id, username) VALUES (%(user_id)s, %(username)s)]
[parameters: {'user_id': 53****, 'username': 'test_testmm_bot'}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

**Comment by PaulSonOfLars** [comment]
https://github.com/PaulSonOfLars/tgbot/issues/110#issuecomment-1048670153

**Comment by Randi356** [comment]
postres to "postresql://"

free links https://customer.elephantsql.com
