### ISSUE TITLE
Feature: Leave from Chat if Added by anyone other than owner

### ISSUE THREAD

**Issue by reyasmohammed** [PaulSonOfLars/tgbot#12]
I am new to Python, as well as telegram bot creation. It will be great if you can guide me to add a piece of code to exit the group if the bot is added to any group, by anyone other than owner of bot. 

I am not able to understand, where should I write that code to exit/leave from group.

**Comment by PaulSonOfLars** [comment]
Explained in t.me/MarieSupport that it would be more logical to just disable groups via bot father. Closing issue.
