### ISSUE TITLE
add chat_lock feature

### ISSUE THREAD

**Issue by c311at** [PaulSonOfLars/tgbot#14]
add chat_lock feature. 
what will this feature do?
messages will be deleted when the command is used.admin messages will not be deleted
as an example, you can look at the bot over there. [for example](https://github.com/OctoNezd/OctoBotPlugins/blob/81127f4e217c410ee553053f9c3afc60ff75d3d6/chat_lock.py)

**Comment by PaulSonOfLars** [comment]
That feature already exists. Look at locking messages.

**Comment by c311at** [comment]
I did not know that it changed this feature.

**Comment by PaulSonOfLars** [comment]
What? It doesn't "change" anything, I'm just saying that's already been implemented.

**Comment by c311at** [comment]
ok thanks

**Comment by PaulSonOfLars** [comment]
Resolved, closing issue
