### ISSUE TITLE
PTB Error, because @username has not interacted with the @bot

### ISSUE THREAD

**Issue by SpEcHiDe** [PaulSonOfLars/tgbot#22]
Having [this](https://github.com/PaulSonOfLars/tgbot/blob/master/tg_bot/__main__.py#L53:26) in message_text causes this: ```telegram.error.BadRequest: Entity_mention_user_invalid```

**Comment by PaulSonOfLars** [comment]
Until I change it, workaround is to forward one of my messages to the bot.

**Comment by PaulSonOfLars** [comment]
Fixed
