### ISSUE TITLE
Feature Request: Deleting service messages

### ISSUE THREAD

**Issue by theallseingeye** [PaulSonOfLars/tgbot#32]
Could you add another option to welcome and goodbye to have have something like /welcome delete to delete the service messages like "Xyz joined the group"

**Comment by theallseingeye** [comment]
Seems we could just add something like:

```
           # Delete message
            update.effective_message.delete()
            continue
```

I'm unsure how to add this into settings, my python skills aren't that great

**Comment by SpEcHiDe** [comment]
This is done [here](https://github.com/SpEcHiDe/PSonOfLars_BHMarie/commit/67d97661edcc42d4ad8c5c569227372312f70fd6#diff-5a4efcd4a356a0783d8f8f03a7aa0933R138)

**Comment by theallseingeye** [comment]
Doesn't that delete the previous welcome message sent by the bot?

I'm looking to delete the telegram service message, ie. "Person joined the group" or "Person was invited to the group by X"

**Comment by SpEcHiDe** [comment]
no. it deletes the current service message.

**Comment by theallseingeye** [comment]
Oh great, that's cool. The wording of of the function (and my lack of python skills) threw me off.

Could we also add a /cleangoodbye
?

**Comment by SpEcHiDe** [comment]
left notifications are only broadcasted after 5 minutes of creation of the group and only in super groups having less than 50 members.

**Comment by theallseingeye** [comment]
Thanks for the clarifications!
