### ISSUE TITLE
inappropriate/unfitting response to the /run command

### ISSUE THREAD

**Issue by 1maverick1** [PaulSonOfLars/tgbot#5]
https://github.com/PaulSonOfLars/tgbot/blob/acc67cb40cb2d3c0f30a6bc191710ce20cc1f59c/tg_bot/modules/misc.py#L31

string on line 31 is inappropriate for /run command. I'd kindly request it to be removed.

**Comment by MSF-Jarvis** [comment]
1) the command is `/runs`
2) MSFJarvis definitely wants to hear about this one

**Comment by smartass08** [comment]
smartass08 too

**Comment by DD3Boh** [comment]
LMFAO
