### ISSUE TITLE
saying goodbye and welcome to other bots when bots are lock

### ISSUE THREAD

**Issue by MohammadMokhalled** [PaulSonOfLars/tgbot#53]
hello
thanks for your good bot
I think it's better not to say goodbye and welcome to bots when bots are lock. because it's like this.
1- say hello to bot
2- remove the bot
3- say only admins can add a bot
4- say goodbye

if admin doesn't like a robot the the robot is not welcome, and when Marie remove some user or but she shouldn't say goodbye.

**Comment by PaulSonOfLars** [comment]
Due to the modular and asynchronous design of tgbot, this can't be changed. I agree it's not ideal, but it's also not a major usability bug.

Feel free to ask more questions and close this issue when you feel your question has been answered

**Comment by MohammadMokhalled** [comment]
thanks for your reply.
