### ISSUE TITLE
Delete welcome message if the user accepts "Are you human"-Button

### ISSUE THREAD

**Issue by Fabio1988** [PaulSonOfLars/tgbot#67]
Hy, as mentioned in title would that be possible? Why should I keep the message when the user accepts it. For other user it's very confusing sometimes. So not only deleting the old ones, also delete the actual one if accepted?! :)

**Comment by PaulSonOfLars** [comment]
I'm not sure I understand the question, tgbot does not have any "are you human" logic

**Comment by Fabio1988** [comment]
sry I meant the mute-button after welcome-message :)

So I set welcomeMessage and set mutetext :)

**Comment by PaulSonOfLars** [comment]
Yes I understand, and that's why I'm saying - tgbot/Marie does not have a mute button on the welcome message.

**Comment by PaulSonOfLars** [comment]
This is not the MissRose bot repo. Miss Rose is closed source - this is the repo for Marie.
Join t.me / RoseSupport for Rose discussions and reasons as to why she's closed source.

**Comment by PaulSonOfLars** [comment]
Closing due to wrong repo :)
