### ISSUE TITLE
fban -> unban - Rose still kicks the user

### ISSUE THREAD

**Issue by Klimmbimmel** [PaulSonOfLars/tgbot#73]
I unfortunately fbanned the wrong id (it was a forwarded message, so the original couldn't be determined). Then I unbanned the user (positive response from Rose) and removed him/her from the list of banned users. When the user wanted to join again, s*he was kickbanned again by Rose. Only adding the user by me (admin) solved the problem. I can add the user id here, if you want to check the logs.

**Comment by PaulSonOfLars** [comment]
This is the repo for tgbot, aka Marie; Rose is not open source. If you have an issue with Rose, please ask in the support chat (available in the /help - won't link here to avoid Internet crawlers)

**Comment by Klimmbimmel** [comment]
I filed this bug report, because I thought it might help your development. I was not here to get help. Greets

**Comment by PaulSonOfLars** [comment]
My point still stands - this is not the right place to report issues with Rose, since it is an unrelated project. 
I believe all issues should be kept in one place, the support chat, hence why I asked you to report any issues there.
Nowhere did I mention you asking for help.

**Comment by Klimmbimmel** [comment]
my mistake: the correct command would have been
/funban

**Comment by PaulSonOfLars** [comment]
I'm going to lock this thread - you are asking in the wrong place.
Please see the rose /help for a link to the support chat.
