### ISSUE TITLE
Notes and filters don't support {} personalisation tags

### ISSUE THREAD

**Issue by eduardstal** [PaulSonOfLars/tgbot#75]

**Comment by PaulSonOfLars** [comment]
Your statement is correct.
Is this a feature request? Or a bug report?
Please provide more details.

**Comment by eduardstal** [comment]
> Your statement is correct.
> Is this a feature request? Or a bug report?
> Please provide more details. 

It's more of a feature request.

**Comment by PaulSonOfLars** [comment]
Ah, that would've been helpful context to add to your issue description.
Anyway, as mentioned in the [readme](https://github.com/PaulSonOfLars/tgbot/blob/master/README.md), this project is no longer under active development.
If you do add this feature and would like to see it merged in here, do feel free to open a PR.
Closing issue.
