### ISSUE TITLE
Ban my number or my area code?!

### ISSUE THREAD

**Issue by vahids** [PaulSonOfLars/tgbot#82]
Hi there, I'm confused!

There are a lot of group in telegram that use Rose bot to manage but I can't send message because of banning my number on it. I think you blocked all +98 codes. but what your logic to did it?!

my number is +98-91********
Why did you block? are u in censorship team or something like that?

**Comment by PaulSonOfLars** [comment]
https://t.me/tgbeta/3734

Iran has been blocked by telegram. This has nothing to do me with me, or Rose. 

Either way, bots can't see your phone number, so blocking on area code would be impossible.

**Comment by vahids** [comment]
Ow F, Seems like I just have one solution,
Register a new account with a number from out side of Iran.

Thanks for your fast replay @PaulSonOfLars
