### ISSUE TITLE
可以在欢迎语里添加图片吗？

### ISSUE THREAD

**Issue by blmulang** [PaulSonOfLars/tgbot#88]
首先感谢制作组。
如题，Markdown里边可以添加发送图片功能吗？

﹉﹉﹉﹉﹉﹉﹉Google translate:
title：Can you add pictures to the welcome message?

content：First of all thanks to the production team.
Like the title, can you add the function of sending pictures in Markdown?
❤️😘

**Comment by PaulSonOfLars** [comment]
reply to the picture with your setwelcome command, and itll save the picture as your welcome message.
