### ISSUE TITLE
complaint mode

### ISSUE THREAD

**Issue by emreordukaya** [PaulSonOfLars/tgbot#95]
Hi, can contributors add complaint mode to Rose.

So someone in group write bad things. Then X number of users(can be adjust by admin) complain this user to admin. then this user who wrote bad things add silent mode or bun or kick. Then admin control the process.

Thanks to contributors.

**Comment by PaulSonOfLars** [comment]
This is not the source code for "rose".

If you have questions and feature requests for rose, please ask in the relevant support chat.

And no, I don't think "voteban" is a good idea.
